version: "3.9"

services:
  postgres:
    image: registry.cn-hangzhou.aliyuncs.com/onesis-geomodels/postgres:14.12-alpine
    container_name: georag-postgres
    restart: always
    environment:
      POSTGRES_DB: georag_dev
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d 

volumes:
  pgdata: